language: php

sudo: false

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run
    - ./vendor/bin/phpstan analyse --level=7 lib
    - ./vendor/bin/phpunit
