language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

jobs:
  include:
    - name: composer 1.x
      php: 7.2
      before_script:
        - composer require composer/composer "^1.8"
      script:
        - composer integrate
    - name: composer 2.x
      php: 7.2
      before_script:
        - composer remove friendsofphp/php-cs-fixer --no-update --dev
        - composer require composer/composer "^2.0"
      script:
        - composer integrate
    - name: PHP 7.3
      php: 7.3
      before_script:
        - composer install
      script:
        - composer integrate
    - name: PHP 7.4
      php: 7.4
      before_script:
        - composer install
      script:
        - composer integrate
